timing:
  -
    start: :donetska
    end: :ukrainska
    time: 6
    price: 3
  -
    start: :ukrainska
    end: :nezalezhna
    time: 4
    price: 2
  -
    start: :nezalezhna
    end: :konotopska
    time: 3.5
    price: 3
  -
    start: :konotopska
    end: :shevchenkivska
    time: 3.5
    price: 3
  -
    start: :shevchenkivska
    end: :heroiv_maidany
    time: 4
    price: 2
  -
    start: :heroiv_maidany
    end: :granychna
    time: 6
    price: 3
  -
    start: :nezalezhna
    end: :banderivska
    time: 3.5
    price: 3
  -
    start: :nezalezhna
    end: :melnykivska
    time: 3
    price: 2.5
  -
    start: :shevchenkivska
    end: :banderivska
    time: 3.5
    price: 3
  -
    start: :shevchenkivska
    end: :melnykivska
    time: 3
    price: 2.5
  -
    start: :banderivska
    end: :sheptyckogo
    time: 6.8
    price: 3.5
  -
    start: :sheptyckogo
    end: :natovska
    time: 5
    price: 2.3
  -
    start: :sheptyckogo
    end: :kiborgiv
    time: 2.4
    price: 1.3
  -
    start: :kiborgiv
    end: :krymska
    time: 7
    price: 3.5
  -
    start: :krymska
    end: :shchaslyva
    time: 8
    price: 4
  -
    start: :shchaslyva
    end: :kiborgiv
    time: 4
    price: 2
  -
    start: :sheptyckogo
    end: :halytska
    time: 2.4
    price: 1.3
  -
    start: :halytska
    end: :lemberska
    time: 6.7
    price: 3.5
  -
    start: :lemberska
    end: :babo_paraskivska
    time: 9
    price: 4.5
  -
    start: :babo_paraskivska
    end: :halytska
    time: 5
    price: 2.5
